### ISSUE TITLE
Codebase: check if custom properties are used

### ISSUE THREAD

**Issue by zoepje** [fdnd-agency/avl#57]

**Comment by itsValyria** [comment]
### What were our custom properties?

We used custom properties for the following things:
- fonts
- font sizes
- colors
- gaps
- paddings
- border radius

### What issues did I find?

When I was looking through our CSS, I found the following issues:

1. **Custom properties naming:** we use font size 1, 2, 3 etc. Better would be to use small, medium, large etc. Same goes for everything that scales, like margin, padding and border radius.
2. **Not all colors we use are a property:** like pure white or some greys. I will add these and adjust the places where they are used.

**Comment by itsValyria** [comment]
### Before

```css
:root {
  --font: sans-serif;
  --heading-font: "rundschrift", sans-serif;

  --font-size-00: .5rem;
  --font-size-0: .75rem;
  --font-size-1: 1rem;
  --font-size-2: 1.125rem;
  --font-size-3: 1.25rem;
  --font-size-4: 1.875rem; 
  --font-size-5: 2rem;
  --font-size-6: 2.5rem;
  --font-size-7: 3rem;
  --font-size-8: 3.5rem;

  --text-color: #000000;
  --alt-text-color: #ffffff;
  --primary-color: #6a0025;
  --background-color: #F0E5E9;
  --background-category-color: #D2B2BD;
  --body-color: rgba(240, 229, 233, 1);

  --gap: .5rem;
  --padding-button: 8px 16px;
  --padding-label: 4px;
  --margin-center: 0 auto;

  --border-radius-small: 5px;
  --border-radius-big: 10px;
  --border-nav: 3px solid var(--primary-color);

  --card-max-width: 384px;

  --focus: solid 2px blue;
}
```

### After
```css

```
